ope. cleanup (#2)
* rm: unnecessary makefile

* chore: slight fixes/changes

* docs: README enhancement

+ bash implementation by: @skateron

diff --git a/zippy-cli b/zippy-cli
--- a/zippy-cli
+++ b/zippy-cli
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Variables
-VERSION="v0.2.0"
+VERSION="v0.2.1"
 download_util="curl"
 base_domain="zippyshare.com"
 
@@ -71,7 +71,7 @@ get_infos(){
 
 # Param "${file_name}" "${id_up}"
 upload_file(){
-	ret_url="$(curl -o "-" -F "upload_form=@${1}" -F "uploadId=${2}" "https://${serv_up}.${base_domain}/upload" -# | sed -E '/<textarea id="names-links" class="file_upload_remote">/,/<\/textarea>/!d;/https/!d')"
+	ret_url="$(curl -ko "-" -F "upload_form=@${1}" -F "uploadId=${2}" "https://${serv_up}.${base_domain}/upload" -# | sed -E '/<textarea id="names-links" class="file_upload_remote">/,/<\/textarea>/!d;/https/!d')"
 	inf "The File Has Been Uploaded"
 	suc "Download Link: ${ret_url}"
 	printf '%s' "${file_name}" | grep -qE 'tmp.zip$' && rm -f "${file_name}"
@@ -82,7 +82,10 @@ downldr_main(){
 	if ! printf '%s' "${url_req}" | grep -q 'zippyshare'; then
 		die "Unsupported Domain"
 	fi
-	ind_urlreq="$(curl -sLk "${url_req}")"
+	if ! ind_urlreq="$(curl -sLfk "${url_req}")"; then
+		err "Failed retrieving download page"
+		return 1
+	fi
 	# simply this sed if the regex fails, it will return nothing and solve will return nothing because theres nothing to slice
 	# sed doesn't change its exit code whenever it fails, Note that "[exit-code]" argument in "q" is a gnu extension, it will not work with other sed variants
 	while [ -z "${solve}" ]; do
@@ -125,16 +128,16 @@ show_help(){
 	
 	 Usage: 
 	     ${0##*/} [-m] [<url>|urls.txt]
-	     ${0##*/} [-f <file|directory>]
+	     ${0##*/} [-f <file|dir>]
 	     ${0##*/} [-v|-h|--aria]
 	
 	 Options:
-	   -f [<file|directory>]\t\t: Insert the File location to Upload
+	   -f [<file|dir>]\t: Insert the File location to Upload
 	   -m\t\t\t: Enable download listing
 	   -o\t\t\t: Output file name
 	   -v\t\t\t: Show the version of the script
 	   -h\t\t\t: Show this help
-	   --aria\t\t: Use Aria2c as Downloader
+	   -a, --aria\t\t: Use Aria2c as Downloader
 	
 	Max file size upload: 500MB
 	EOF
@@ -168,13 +171,13 @@ main(){
 		get_file_dir "${file_dir}"
 		checkif "${file_dir}"
 		is_dir "${file_dir}"
-		get_infos
+		get_infos || die "An error occured while retrieving IDs"
 		upload_file "${file_name}" "${id_up}"
 	fi
 }
 
 arg_parser(){
-	while getopts ":vhmf:o:-:" opt; do
+	while getopts ":vhmaf:o:-:" opt; do
 		case "${opt}" in
 			v)
 				printf '%s\n' "${VERSION}"
@@ -198,6 +201,10 @@ arg_parser(){
 						file_dir="${OPTARG}"
 						;;
 				esac
+				;;
+			a)
+				dep_check "aria2c"
+				download_util="aria2c"
 				;;
 			o)
 				file_out="${OPTARG}"
