feat. multi-pattern scraping
# pretty much for longer scraping life of the script, i'll just add the new ones if all scraping brokes

diff --git a/zippy-cli b/zippy-cli
--- a/zippy-cli
+++ b/zippy-cli
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Variables
-VERSION="v0.1.4"
+VERSION="v0.2.0"
 download_util="curl"
 base_domain="zippyshare.com"
 
@@ -82,22 +82,39 @@ downldr_main(){
 	if ! printf '%s' "${url_req}" | grep -q 'zippyshare'; then
 		die "Unsupported Domain"
 	fi
+	ind_urlreq="$(curl -sLk "${url_req}")"
 	# simply this sed if the regex fails, it will return nothing and solve will return nothing because theres nothing to slice
 	# sed doesn't change its exit code whenever it fails, Note that "[exit-code]" argument in "q" is a gnu extension, it will not work with other sed variants
-	ind="$(curl -sLk "${url_req}" | sed -nE 's_.*document.getElementById.*dl.*.href.*"(/d/[^\"]*)".*\(([^\)]*)\).*"([^\"]+)".*_\1#\2#\3_p')"
-	solve="${ind#*#}"
-	[ -z "${solve%%#*}" ] && die "An error occured"
-	if printf '%s' "${solve%%#*}" | grep -qE '^([0-9\-\+\*%/ ]*)$'; then
-		solve="$((${solve%%#*}))"
-	else
-		die "An error occured"
-	fi
+	while [ -z "${solve}" ]; do
+		[ "${is_success}" = "true" ] || : "$((ind_iter += 1))"
+		case "${ind_iter}" in
+			1)
+				ind="$(printf '%s' "${ind_urlreq}" | sed -nE 's_.*document.getElementById.*dl.*.href.*"(/d/[^\"]*)"\+\(([^\+]*)+.*"([^\"]*)"\;_\1#\2+11#\3_p')"
+				;;
+			2)
+				ind="$(printf '%s' "${ind_urlreq}" | sed -nE 's_.*document.getElementById.*dl.*.href.*"(/d/[^\"]*)".*\(([^\)]*)\).*"([^\"]+)".*_\1#\2#\3_p')"
+				;;
+			*)
+				die "Failed to fetch scrapings, probably the algorithm changed again"
+				;;
+		esac
+		solve="${ind#*#}"
+		if [ -n "${solve%%#*}" ] && printf '%s' "${solve%%#*}" | grep -qE '^([0-9\-\+\*%/ ]*)$'; then
+			solve="$((${solve%%#*}))"
+			is_success="true"	# No need to iterate through patterns if success (for multi-links)
+		else
+			err "Pattern #${ind_iter} failed"
+			unset solve ind
+		fi
+	done
 	col="${url_req%%/v/*}$(printf '%s' "${ind}" | sed -E "s_\#(.*?)\#_${solve}_g")"
-	if "${download_util}" "${col}" -o "${col##*/}"; then
+	[ -z "${file_out}" ] && file_out="${col##*/}"
+	if "${download_util}" "${col}" -o "${file_out}"; then
 		suc "File \"${col##*/}\" was successfully downloaded"
 	else
 		err "Returned an Error while downloading \"${col##*/}\""
 	fi
+	unset ind ind_urlreq
 }
 
 show_help(){
@@ -114,6 +131,7 @@ show_help(){
 	 Options:
 	   -f [<file|directory>]\t\t: Insert the File location to Upload
 	   -m\t\t\t: Enable download listing
+	   -o\t\t\t: Output file name
 	   -v\t\t\t: Show the version of the script
 	   -h\t\t\t: Show this help
 	   --aria\t\t: Use Aria2c as Downloader
@@ -156,7 +174,7 @@ main(){
 }
 
 arg_parser(){
-	while getopts ":vhmf:-:" opt; do
+	while getopts ":vhmf:o:-:" opt; do
 		case "${opt}" in
 			v)
 				printf '%s\n' "${VERSION}"
@@ -180,6 +198,9 @@ arg_parser(){
 						file_dir="${OPTARG}"
 						;;
 				esac
+				;;
+			o)
+				file_out="${OPTARG}"
 				;;
 			-)
 				case "${OPTARG}" in
@@ -211,6 +232,7 @@ arg_parser(){
 		esac
 	done
 	shift "$((OPTIND -1))"
+	[ "${m_dl}" = "true" ] && [ -n "${file_out}" ] && die "Output file name only applied when downloading only single file"
 	[ -n "${1}" ] && loopdl="${1}" && is_dl="true"
 }
 
