fix: zippy new algo
+ few improvements

diff --git a/zippy-cli b/zippy-cli
--- a/zippy-cli
+++ b/zippy-cli
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Variables
-VERSION="v0.1.3"
+VERSION="v0.1.4"
 download_util="curl"
 base_domain="zippyshare.com"
 
@@ -51,7 +51,7 @@ is_dir(){
 	file_name="${1}"
 	if [ -d "${file_name}" ]; then
 		dep_check "zip"
-		file_name="${1##*/}.zip"
+		file_name="${1##*/}.tmp.zip"
 		zip -r -o "${file_name}" "${1}" >/dev/null 2>&1
 	fi
 	if [ "$(stat -c '%s' "${file_name}")" -gt 524288000 ]; then
@@ -61,9 +61,12 @@ is_dir(){
 }
 
 get_infos(){
-	index_jsp="$(curl -sLk "https://www.${base_domain}/sites/index_old.jsp")"
+	index_jsp="$(curl -sLfk "https://www.${base_domain}/sites/index_old.jsp")" || return 1
 	id_up="$(printf '%s' "${index_jsp}" | sed -E '/var.*uploadId/!d;s_.*=.\x27([^\x27]*)\x27.*_\1_')"
 	serv_up="$(printf '%s' "${index_jsp}" | sed -E '/var.*server/!d;s_.*=.\x27([^\x27]*)\x27.*_\1_')"
+	if [ -z "${id_up}" ] || [ -z "${serv_up}" ]; then
+		die "An error occured"
+	fi
 }
 
 # Param "${file_name}" "${id_up}"
@@ -71,7 +74,7 @@ upload_file(){
 	ret_url="$(curl -o "-" -F "upload_form=@${1}" -F "uploadId=${2}" "https://${serv_up}.${base_domain}/upload" -# | sed -E '/<textarea id="names-links" class="file_upload_remote">/,/<\/textarea>/!d;/https/!d')"
 	inf "The File Has Been Uploaded"
 	suc "Download Link: ${ret_url}"
-	[ "${file_name##*.}" = "zip" ] && rm -f "${file_name}"
+	printf '%s' "${file_name}" | grep -qE 'tmp.zip$' && rm -f "${file_name}"
 }
 
 downldr_main(){
@@ -81,7 +84,7 @@ downldr_main(){
 	fi
 	# simply this sed if the regex fails, it will return nothing and solve will return nothing because theres nothing to slice
 	# sed doesn't change its exit code whenever it fails, Note that "[exit-code]" argument in "q" is a gnu extension, it will not work with other sed variants
-	ind="$(curl -sLk "${url_req}" | sed -nE 's_.*document.getElementById.*dl.*.href.*"(/d/[^\"]*)"\+\(([^\+]*)+.*"([^\"]*)"\;_\1#\2+11#\3_p')"
+	ind="$(curl -sLk "${url_req}" | sed -nE 's_.*document.getElementById.*dl.*.href.*"(/d/[^\"]*)".*\(([^\)]*)\).*"([^\"]+)".*_\1#\2#\3_p')"
 	solve="${ind#*#}"
 	[ -z "${solve%%#*}" ] && die "An error occured"
 	if printf '%s' "${solve%%#*}" | grep -qE '^([0-9\-\+\*%/ ]*)$'; then
@@ -104,13 +107,12 @@ show_help(){
 	Simple program that allows you to upload/download files via command line.
 	
 	 Usage: 
-	     ${0##*/} [-f <file>]
-	     ${0##*/} [-m] -d [<url>|urls.txt]
+	     ${0##*/} [-m] [<url>|urls.txt]
+	     ${0##*/} [-f <file|directory>]
 	     ${0##*/} [-v|-h|--aria]
 	
 	 Options:
-	   -f "<file>"\t\t: Insert the File location to Upload
-	   -d "<url>"\t\t: Download a File from ZippyShare
+	   -f [<file|directory>]\t\t: Insert the File location to Upload
 	   -m\t\t\t: Enable download listing
 	   -v\t\t\t: Show the version of the script
 	   -h\t\t\t: Show this help
@@ -154,7 +156,7 @@ main(){
 }
 
 arg_parser(){
-	while getopts ":vhmf:d:-:" opt; do
+	while getopts ":vhmf:-:" opt; do
 		case "${opt}" in
 			v)
 				printf '%s\n' "${VERSION}"
@@ -179,46 +181,39 @@ arg_parser(){
 						;;
 				esac
 				;;
-			d)
-				case "${OPTARG}" in
-					-*)
-						err "File Location is Not Specified"
-						show_help
-						exit 1
-						;;
-					*)
-						is_dl="true"
-						loopdl="${OPTARG}"
-						;;
-				esac
-				;;
 			-)
 				case "${OPTARG}" in
 					aria)
 						dep_check "aria2c"
 						download_util="aria2c"
-					;;
+						;;
 					help)
 						show_help
 						exit 0
-					;;
+						;;
+					*)
+						err "[--${OPTARG}]: Illegal Option"
+						show_help
+						exit 1
+						;;
 				esac
 				;;
 			\?)
-				err "[${OPTARG}] : is not valid Argument"
+				err "[-${OPTARG}]: is not valid Argument"
 				show_help
 				exit 1
 				;;
 			:)
-				err "[-${OPTARG}] : Argument must have a Value"
+				err "[-${OPTARG}]: Argument must have a Value"
 				show_help
 				exit 1
 				;;
 		esac
 	done
 	shift "$((OPTIND -1))"
+	[ -n "${1}" ] && loopdl="${1}" && is_dl="true"
 }
 
-dep_check "grep" "curl" "stat" "sed" "awk"
+dep_check "grep" "curl" "stat" "sed"
 arg_parser "${@}"
 main
